 steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/ms-file:$COMMIT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/ms-file:$COMMIT_SHA']
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: bash
   args:
   - 'deploy.sh'
   - '$PROJECT_ID'
   - '$COMMIT_SHA'
 images:
 - 'gcr.io/$PROJECT_ID/ms-file:$COMMIT_SHA'